# Воркшоп #1: Працюємо з NumPy

Вітаю на першому воркшопі нашого курсу!

Нагадую, що наші воркшопи складатимуться з трьох частин:
- "Підготовча" частина, яку ви виконуєте ДО відповідного воркшопу
- "Спільна" частина, яку ви виконуєте під час відповідного воркшопу
- "Домашня" частина, яку ви виконуєте самостійно і за яку отримуєте бали :)

Власне...
### ПОЧАТОК ПІДГОТОВЧОЇ ЧАСТИНИ

Давайте познайомимось. Цей воркшоп виконує...:


Супер!

Перш ніж почнемо знайомство з NumPy, давайте його імпортуємо за допомогою рядка `import numpy as np`:

In [ ]:
import numpy as np

Чудово! 

> **!!!** Надалі, щоб не обтяжувати вас читанням купи додаткових слів, цей шаблон воркшопу (як і наступні після нього) просто пропонуватимуть вам зробити певні кроки. Іноді до таких кроків будуть підказки, іноді вам доведеться самостійно згадати матеріали з лекцій, а іноді не залишиться нічого, окрім як заглянути в документацію.
> 
> Мета усіх цих кроків - щоб дорогою ви опанували, власне, матеріал воркшопу. Краще один раз надрукувати руцями, ніж сто разів прослухати лекцію.

Почнемо. Ось ваше перше завдання: створіть змінну `v1`, яка представлятиме з себе **вектор-рядок** з натуральних чисел від 1 до 5 (включно). Для цього використайте функцію arange, попередньо переглянувши її документацію за допомогою `?np.arange`


In [7]:
v1 = np.arange(1,6)

Тепер перевіримо, чи все у вас вийшло так, як треба. Запустіть наступний рядок і переконайтесь, що бачите очікуваний результат. 

In [8]:
assert isinstance(v1, np.ndarray)
assert len(v1) == 5

v1

array([1, 2, 3, 4, 5])

Також створіть матрицю `A` розміру 5x7 [*], заповнену одиницями. Круто, якщо знаєте декілька варіантів, як це зробити, можете показати їх усі :) 

[*] Такий запис (незалежно від кількості вимірів) типово починається з "зовнішнього" виміру і закінчується "внутрішнім". У даному випадку, 5х7 означає матрицю з 5-ма рядками і 7-ма стовпчиками.

In [9]:
A =np.ones((5, 7), dtype=int)

Перевіряємо:

In [43]:
A

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

Щоб було не так нудно працювати з цією матрицею, давайте одразу замінимо усі одиниці на перетині стовпчиків 2-5 та рядків 1-4 на **четвірки**. Іншими словами, я хочу щоб змінна `A` містила наступу матрицю:   

$$
\begin{pmatrix}
1 & 4 & 4 & 4 & 4 & 1 & 1 \\
1 & 4 & 4 & 4 & 4 & 1 & 1 \\
1 & 4 & 4 & 4 & 4 & 1 & 1 \\
1 & 4 & 4 & 4 & 4 & 1 & 1 \\
1 & 1 & 1 & 1 & 1 & 1 & 1 \\
\end{pmatrix}
$$

Не забудьте перевірити, що результат саме такий, як хочеться.

In [10]:
A[0:4 , 1:5] = 4

A

array([[1, 4, 4, 4, 4, 1, 1],
       [1, 4, 4, 4, 4, 1, 1],
       [1, 4, 4, 4, 4, 1, 1],
       [1, 4, 4, 4, 4, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

На цьому поки все, зустрінемось в аудиторії 😉 

### КІНЕЦЬ ПІДГОТОВЧОЇ ЧАСТИНИ
-----------------------------
### ПОЧАТОК СПІЛЬНОЇ ЧАСТИНИ

Додатково додамо одиничку до пʼяти елементів - до третього елемента у першому рядку, четвертого елемента у другому рядку, пʼятого елемента у третьому рядку і тд. Іншими словами, хочемо отримати наступну матрицю: 

$$
\begin{pmatrix}
1 & 4 & 5 & 4 & 4 & 1 & 1 \\
1 & 4 & 4 & 5 & 4 & 1 & 1 \\
1 & 4 & 4 & 4 & 5 & 1 & 1 \\
1 & 4 & 4 & 4 & 4 & 2 & 1 \\
1 & 1 & 1 & 1 & 1 & 1 & 2 \\
\end{pmatrix}
$$
Обовʼязково впевніться, що результат той, що ви хочете, і що ви не зробили одну й ту саму дію декілька разів!

In [11]:
A[0,2] +=1
A[1,3] +=1
A[2,4] +=1
A[3,5] +=1
A[4,6] +=1
A

array([[1, 4, 5, 4, 4, 1, 1],
       [1, 4, 4, 5, 4, 1, 1],
       [1, 4, 4, 4, 5, 1, 1],
       [1, 4, 4, 4, 4, 2, 1],
       [1, 1, 1, 1, 1, 1, 2]])

Тепер трохи пограємося з `A` та `b`. Отримайте матрицю $C$ розміром, кожен елемент якої на 3 менший, ніж подвоєний відповідний елемент матриці $A$.

In [18]:
C = (2 * A) - 3
C

array([[-1,  5,  7,  5,  5, -1, -1],
       [-1,  5,  5,  7,  5, -1, -1],
       [-1,  5,  5,  5,  7, -1, -1],
       [-1,  5,  5,  5,  5,  1, -1],
       [-1, -1, -1, -1, -1, -1,  1]])

Тепер я хочу отримати вектор `d`, який є результатом множення вектора $b$ на матрицю $C$. Тут одразу питання - у цьому випадку вектор на матрицю доведеться множити зліва чи справа? 

У будь-якому разі, підказка - скористайтесь оператором `@`.

In [ ]:
b = v1

d = b @ C
d

array([-15,  45,  47,  49,  51,  -7,  -5])

Тепер подивіться на скалярний добуток вектора `d` самого на себе. Має вийти 9535 :)  

In [25]:
sc = d @ d
sc

np.int64(9535)

### Математичні функції

Окрім операторів, numpy надає нам купу різних функцій для взаємодії з n-вимірними масивами. `np.sin`, `np.exp`, `np.pow`, ... - коротше, все, чого душа забажає. 

Знаючи цей факт, можливо здогадаєтесь, як порахувати 
$$ \sum_{i=1}^{2'000'000} e^{\sin i \cdot \cos 1/i} $$ 

In [59]:
%%timeit
import numpy as np

i = np.arange(1, 2000001)
res = np.sum(np.pow(np.e, (np.sin(i) * np.cos(1 / i))))
res

93.4 ms ± 2.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Має вийти щось близьке до $2532130.799$. Скористайтесь `%%timeit`, щоб поглянути, скільки зайняли обчислення, які ви написали.

Цікаво, а скільки б зайняло це обчислення, якби ви замість numpy використали звичайний python? Що ж, запустіть наступні дві комірки, щоб поглянути:

In [61]:
from math import sin as m_sin, cos as m_cos, exp as m_exp

In [62]:
%%timeit 

result = 0
for i in range(1, 2*1000*1000 + 1):
    result += m_exp(m_sin(i) * m_cos(1 / i))

483 ms ± 24.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


До речі, можливо, у вас є здогадки, чому `from math import sin as m_sin, cos as m_cos, exp as m_exp` винесено окремою коміркою? 
І чому ми користуємось `m_sin` замість того, щоб писати `math.sin`? 

--------------------

Сподіваюсь, з перекладом інших формул з математичних нотацій на "мову NumPy" проблем не виникне.

Давайте поглянемо, що ще є в NumPy. 
`numpy.linalg` - потужний модуль, який розвʼязує основні підзадачі лінійної алгебри.

Давайте, до прикладу, знайдемо матрицю, обернену до:
$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 10
\end{pmatrix}
$$

Що ж, спершу дізнаємось, чи це взагалі можливо. Який критерій обертновності матриці? Здогадаєтесь, яка функція у `np.linalg` відповідає за це?


In [101]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

In [68]:
DET = np.linalg.det(matrix)
DET != 0


np.True_

Тепер, якщо ми вже знаємо, що матриця обертовна, давайте таки знайдемо обернену до неї. Вам знадобиться функція `np.linalg.inv`.

Запишіть матрицю у змінну `INV`

In [102]:
INV = np.linalg.inv(matrix)
INV

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

Тепер давайте трохи пограємося з матрицею `INV`. Перш за все, спробуємо отримати усі елементи, які менші за 0.5, у вигляді вектора:

In [103]:
sel_inv = INV[INV < 0.5]
sel_inv


array([-0.66666667, -1.33333333, -0.66666667, -2.        , -2.        ])

Супер! Тепер давайте спробуємо домножити відповідні елементи на 2. Наша мета - щоб сама матриця `INV` змінилася, а не ваш новий вектор.

In [104]:
INV[INV < 0.5] *= 2
INV


array([[-1.33333333, -2.66666667,  1.        ],
       [-1.33333333,  3.66666667, -4.        ],
       [ 1.        , -4.        ,  1.        ]])

Круто! 
Тепер давайте для кожного елемента, який менший за 0.3, спробуємо застосувати наступну функцію:
$$ f(x) = x^2 - sin(x) $$

Тут є декілька варіантів, але спробуйте в першу чергу розібратися з тим, як працює `vectorize`

In [105]:
def f(x):
    return np.pow(x, 2) - np.sin(x)

vectorized_f = np.vectorize(f)
boolean_mask = INV < 0.3

INV[boolean_mask] = vectorized_f(INV[boolean_mask])
INV

array([[ 2.74971568,  7.56838374,  1.        ],
       [ 2.74971568,  3.66666667, 15.2431975 ],
       [ 1.        , 15.2431975 ,  1.        ]])

Давайте тепер спробуємо обернути матрицю 
$$
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$$
Лінійна алгебра нам каже, що обернути цю матрицю не можна, але що каже NumPy?  

In [27]:
m_2 = np.array([[1, 2 , 3],[4, 5, 6],[7, 8, 9]])
m_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
DET = np.linalg.det(m_2)
DET != 0


np.False_

In [29]:
INV_2 = np.linalg.inv(m_2)
INV_2

## неможливл знайти інвертовану матрицю

LinAlgError: Singular matrix

```
Тут у вас могло виникнути два абсолютно різних результати. Порівняйте це з результатами колег і обговоріть разом з практиком, що ж могло піти не так
```

------------------


Матриці то добре, але NumPy може стати у нагоді навіть школяреві. Погляньте, що з себе представляє функція np.linalg.solve. Після цього спробуйте вирішити систему лінійних рівнянь:
$$
\begin{align*}
x + 4y - 2z &= 1 \\
2x + 4z &= 2 \\
-3x + 2y + 3z &= 3
\end{align*}
$$


In [30]:
A = np.array([[1, 4, -2],
              [2, 0, 4],
              [-3, 2, 3]])

b = np.array([1, 2, 3])

x = np.linalg.solve(A, b)
x

array([-0.09090909,  0.54545455,  0.54545455])

### КІНЕЦЬ СПІЛЬНОЇ ЧАСТИНИ
-----------------------------
### ПОЧАТОК ДОМАШНЬОЇ ЧАСТИНИ

    Ми вже трохи поглянули, наскільки NumPy швидше, ніж самописний код. Але іноді він буває непристойно швидше, особливо порівнюючи з кодом повністю на Python.

    Ваше завдання наступне: спробуйте написати звичайний алгоритм для множення двох матриць (використовуйте лише звичайний list та конструкції Python, без NumPy) і протестуйте його на матрицях розміру 200x200. Порівняйте це зі швидкістю NumPy. Зробіть висновки :)

    Матриці, які треба помножити, а також матриця для запису результату любʼязно створені нижче


In [21]:


M1 = [[i] * 200 for i in range(200)]
M2 = [[i + 1] * 200 for i in range(200)]

M_RES = [[0] * 200 for i in range(200)]


In [22]:

for i in range (len(M1)):
    for j in range(len(M1[0])):
        for k in range(200):
            M_RES[i][j] += M1[i][k] * M2[k][j]

print(M_RES)


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 20100, 2010

In [23]:

M1_np = np.array(M1)
M2_np = np.array(M2)

M_RES_np = M1_np @ M2_np
M_RES_np



array([[      0,       0,       0, ...,       0,       0,       0],
       [  20100,   20100,   20100, ...,   20100,   20100,   20100],
       [  40200,   40200,   40200, ...,   40200,   40200,   40200],
       ...,
       [3959700, 3959700, 3959700, ..., 3959700, 3959700, 3959700],
       [3979800, 3979800, 3979800, ..., 3979800, 3979800, 3979800],
       [3999900, 3999900, 3999900, ..., 3999900, 3999900, 3999900]],
      shape=(200, 200))

In [ ]:
""" Різниця між швидкістю numpy та звичвйною конструкцією Python склала майже 230 разів на користь numpy"""

In [24]:
M_RES == M_RES_np

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], shape=(200, 200))

На цьому моменті у вас, можливо, зʼявилось питання - а чи включати перетворення з "списку списків" у `np.array` у підрахунок швидкодії. Відповідь тут наступна - поміряйте, наскільки великий ефект це дає, а висновки на майбутнє зробіть самі. 


In [47]:
%%timeit
np1 = np.arange(200).reshape(200, 1) * np.ones((1, 200), dtype=int)
np2 = (np.arange(200).reshape(200, 1) + 1) * np.ones((1, 200), dtype=int)

np_res = np1 @ np2
np_res

9.37 ms ± 297 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
%%timeit
M1 = [[i] * 200 for i in range(200)]
M2 = [[i + 1] * 200 for i in range(200)]

M_RES = [[0] * 200 for i in range(200)]

for i in range (len(M1)):
    for j in range(len(M1[0])):
        for k in range(200):
            M_RES[i][j] += M1[i][k] * M2[k][j]

666 ms ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [49]:
%%timeit
M1 = [[i] * 200 for i in range(200)]
M2 = [[i + 1] * 200 for i in range(200)]

M_RES = [[0] * 200 for i in range(200)]

M1_np = np.array(M1)
M2_np = np.array(M2)

M_RES_np = M1_np @ M2_np



12.9 ms ± 288 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
